spring:
  application:
    name: EmployeeApplication

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/empdb
    username: root
    password: ammu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true

server:
  port: 9092
